### your site title here

title: Samuel Mayworm
description: MSI at the University of Michigan School of Information


### let's use the minima theme (see https://github.com/jekyll/minima)

theme: jekyll-theme-minimal


### exclude the instructions / write-up in the README.md

exclude:
- README.md
