# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: mayworms.info
name: "Samuel Reiji Mayworm"
pronouns: "he/him"
description: "sam's website lol"
email: mayworms@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  Samuel Mayworm's personal website
twitter_username: mayworm_s
github_username: mayworms
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Detroit #https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones America/Detroit

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-toc

author:
  name   : "Samuel Mayworm"
  avatar : "/assets/images/profile-photo.jpg"
  bio    : "PhD Student at the University of Michigan School of Information. Researching trans-centered online communities, alternative online infrastructures, and content moderation. 👋😃"
  links:
   #- label: "CV"
   #- icon: "fas fa-fw fa-link"
   #- url: "files/websitecv2.pdf"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mayworms@umich.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sammayworm/"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0009-0008-8394-7991"
    - label: "Bluesky"
      #icon: "fab fa-fw fa-bluesky"
      icon: "fas fa-fw fa-cloud"
      url: "https://bsky.app/profile/mayworms.bsky.social"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mayworm_s"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mayworms"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://www.instagram.com/mt.eigh/"

footer:
  links:
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/mayworm_s"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/mayworms"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://www.instagram.com/mt.eigh/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
